### ISSUE TITLE
Module did not self register

### ISSUE THREAD

**Issue by Hariskool** [muffinista/hide-cursor#1]
![error](https://user-images.githubusercontent.com/31043660/92605200-e0612580-f2ca-11ea-8228-6da565696c4a.PNG)

**Comment by muffinista** [comment]
Sorry for the delay on this, somehow I missed the original notification. This is working for me so I might need some details on how exactly you're compiling/etc.

**Comment by danielehrhardt** [comment]
Same Issue on Mac here.
I use Typescript:
```
Uncaught Exception:
Error: Module did not self-register: '/node_modules/hide-cursor/build/Release/HideCursor.node'.

```

**Comment by muffinista** [comment]
@Hariskool @danielehrhardt If either of you are able to put together a more detailed example of this or point me towards a specific example of failing code, that would be very helpful for me, thanks.

**Comment by danielehrhardt** [comment]
> @Hariskool @danielehrhardt If either of you are able to put together a more detailed example of this or point me towards a specific example of failing code, that would be very helpful for me, thanks.

https://github.com/danielehrhardt/demo-hide-cursor

**Comment by muffinista** [comment]
@danielehrhardt thanks for this. I'm able to build and run this project without any apparent problems in OSX. Can you let me know:

- What version of node/npm you are using
- Exactly what you run to get the error
- If clearing out your `node_modules` directory and reinstalling fixes the problem

Thanks!

**Comment by Hariskool** [comment]
`node v 10.16.0`
`npm v 6.9.0`
with visual studio build tools 2015 @muffinista

**Comment by danielehrhardt** [comment]
![image](https://user-images.githubusercontent.com/19570043/113508425-3d1a7b00-9550-11eb-857a-1327e0ba17e6.png)
```
node -v
v14.15.4
```

**Comment by danielehrhardt** [comment]
> ![image](https://user-images.githubusercontent.com/19570043/113508425-3d1a7b00-9550-11eb-857a-1327e0ba17e6.png)
> 
> ```
> node -v
> v14.15.4
> ```

I reinstalled the packages and now it does work. 
I will test tomorrow on my Windows PC

**Comment by muffinista** [comment]
OK, assuming that fixes it, hooray! I'm going to close this for now. If it happens again, please let me know the sequence of commands which causes it. Thanks!
