### ISSUE TITLE
Outdated npm version

### ISSUE THREAD

**Issue by onikienko** [muffinista/hide-cursor#8]
Hi @muffinista 

Thank you for this package. 
Could you please publish a new version with updated compiler flags (c++20) to npm? The published v0.0.3 has c++17, and it does not work with the latest electron on Windows.

**Comment by muffinista** [comment]
Absolutely! Just did that, please let me know if you have any issues.

**Comment by onikienko** [comment]
Thank you very much. 
I could build with a new v0.0.4 on MacOS and Windows. It works.
